import type {CarouselTheme} from "./types";

const threeByFourCanvas = {width: 1080, height: 1440};

export const defaultCarouselTheme: CarouselTheme = {
  canvas: {width: 1080, height: 1350},
  spacing: {
    outerX: 88,
    outerY: 88,
    previewGap: 40,
  },
  colors: {
    bg: "#070709",
    fg: "#f4efe7",
    muted: "#b4aa9b",
    accent: "#b8965c",
    overlayStrong: "rgba(6, 6, 8, 0.82)",
    overlaySoft: "rgba(8, 8, 10, 0.34)",
    panel: "rgba(14, 14, 18, 0.9)",
    panelBorder: "rgba(255, 244, 224, 0.11)",
  },
  typography: {
    displayFamily:
      "\"Barlow Condensed\", \"Arial Narrow\", \"Helvetica Neue\", Helvetica, Arial, sans-serif",
    bodyFamily:
      "\"Manrope Variable\", \"Helvetica Neue\", Helvetica, Arial, sans-serif",
    labelSize: 19,
    counterSize: 18,
    coverTitleLarge: 132,
    coverTitleMedium: 116,
    coverTitleSmall: 102,
    subtitleSize: 24,
    promptHeadingSize: 24,
    promptBodySize: 27,
    metaSize: 18,
    ctaSize: 20,
  },
  radius: {
    panel: 32,
  },
};

export const editorialV2Theme: CarouselTheme = {
  ...defaultCarouselTheme,
  colors: {
    ...defaultCarouselTheme.colors,
    fg: "#f6f1e8",
    muted: "#bcb1a1",
    accent: "#c3a06a",
    panel: "rgba(15, 15, 19, 0.82)",
    panelBorder: "rgba(255, 241, 214, 0.14)",
  },
  typography: {
    ...defaultCarouselTheme.typography,
    displayFamily: "\"Cormorant Garamond\", Georgia, serif",
    bodyFamily: "\"Inter Tight\", \"Helvetica Neue\", Helvetica, Arial, sans-serif",
    coverTitleLarge: 138,
    coverTitleMedium: 122,
    coverTitleSmall: 104,
    subtitleSize: 22,
    promptHeadingSize: 30,
    promptBodySize: 22,
    metaSize: 17,
    ctaSize: 18,
  },
};

export const studioV3Theme: CarouselTheme = {
  ...defaultCarouselTheme,
  spacing: {
    ...defaultCarouselTheme.spacing,
    outerX: 94,
    outerY: 94,
  },
  colors: {
    ...defaultCarouselTheme.colors,
    bg: "#060607",
    fg: "#f2efe9",
    muted: "#9d9891",
    accent: "#8b8174",
    overlayStrong: "rgba(7, 7, 9, 0.88)",
    overlaySoft: "rgba(8, 8, 10, 0.2)",
    panel: "rgba(12, 12, 15, 0.9)",
    panelBorder: "rgba(255, 255, 255, 0.08)",
  },
  typography: {
    ...defaultCarouselTheme.typography,
    displayFamily: "\"Sora Variable\", \"Helvetica Neue\", Helvetica, Arial, sans-serif",
    bodyFamily: "\"Inter Tight\", \"Helvetica Neue\", Helvetica, Arial, sans-serif",
    labelSize: 17,
    counterSize: 17,
    coverTitleLarge: 90,
    coverTitleMedium: 80,
    coverTitleSmall: 70,
    subtitleSize: 20,
    promptHeadingSize: 22,
    promptBodySize: 22,
    metaSize: 16,
    ctaSize: 17,
  },
  radius: {
    panel: 22,
  },
};

export const monolithV4Theme: CarouselTheme = {
  ...defaultCarouselTheme,
  canvas: threeByFourCanvas,
  spacing: {
    outerX: 96,
    outerY: 98,
    previewGap: 40,
  },
  colors: {
    ...defaultCarouselTheme.colors,
    fg: "#f4eee3",
    muted: "#a9a092",
    accent: "#b88f59",
    overlayStrong: "rgba(6, 6, 8, 0.86)",
    panel: "rgba(12, 12, 16, 0.9)",
  },
  typography: {
    ...defaultCarouselTheme.typography,
    displayFamily: "\"Archivo Black\", \"Helvetica Neue\", Helvetica, Arial, sans-serif",
    bodyFamily: "\"Inter Tight\", \"Helvetica Neue\", Helvetica, Arial, sans-serif",
    labelSize: 18,
    counterSize: 18,
    coverTitleLarge: 122,
    coverTitleMedium: 108,
    coverTitleSmall: 94,
    subtitleSize: 22,
    promptBodySize: 24,
  },
};

export const galleryV5Theme: CarouselTheme = {
  ...defaultCarouselTheme,
  canvas: threeByFourCanvas,
  spacing: {
    outerX: 92,
    outerY: 92,
    previewGap: 40,
  },
  colors: {
    ...defaultCarouselTheme.colors,
    fg: "#f6f1e7",
    muted: "#b5ac9d",
    accent: "#c5a77c",
    panel: "rgba(18, 17, 20, 0.82)",
    panelBorder: "rgba(255, 242, 214, 0.16)",
  },
  typography: {
    ...defaultCarouselTheme.typography,
    displayFamily: "\"DM Serif Display\", Georgia, serif",
    bodyFamily: "\"Inter Tight\", \"Helvetica Neue\", Helvetica, Arial, sans-serif",
    labelSize: 16,
    counterSize: 17,
    coverTitleLarge: 116,
    coverTitleMedium: 104,
    coverTitleSmall: 92,
    subtitleSize: 20,
    promptHeadingSize: 28,
    promptBodySize: 22,
  },
  radius: {
    panel: 28,
  },
};

export const sideRailV6Theme: CarouselTheme = {
  ...defaultCarouselTheme,
  canvas: threeByFourCanvas,
  spacing: {
    outerX: 88,
    outerY: 94,
    previewGap: 40,
  },
  colors: {
    ...defaultCarouselTheme.colors,
    bg: "#07080a",
    fg: "#edf0f2",
    muted: "#98a1a7",
    accent: "#7d8a96",
    overlayStrong: "rgba(7, 8, 10, 0.88)",
    panel: "rgba(13, 15, 18, 0.92)",
    panelBorder: "rgba(255, 255, 255, 0.08)",
  },
  typography: {
    ...defaultCarouselTheme.typography,
    displayFamily: "\"Space Grotesk\", \"Helvetica Neue\", Helvetica, Arial, sans-serif",
    bodyFamily: "\"Inter Tight\", \"Helvetica Neue\", Helvetica, Arial, sans-serif",
    labelSize: 15,
    counterSize: 16,
    coverTitleLarge: 92,
    coverTitleMedium: 82,
    coverTitleSmall: 72,
    subtitleSize: 19,
    promptHeadingSize: 22,
    promptBodySize: 21,
  },
  radius: {
    panel: 22,
  },
};

export const bottomBandV7Theme: CarouselTheme = {
  ...defaultCarouselTheme,
  canvas: threeByFourCanvas,
  spacing: {
    outerX: 90,
    outerY: 90,
    previewGap: 40,
  },
  colors: {
    ...defaultCarouselTheme.colors,
    fg: "#f3efe6",
    muted: "#aba596",
    accent: "#9e8b69",
    overlayStrong: "rgba(8, 8, 10, 0.78)",
    panel: "rgba(12, 12, 14, 0.92)",
    panelBorder: "rgba(255, 255, 255, 0.08)",
  },
  typography: {
    ...defaultCarouselTheme.typography,
    displayFamily: "\"Barlow Condensed\", \"Arial Narrow\", \"Helvetica Neue\", Helvetica, Arial, sans-serif",
    bodyFamily: "\"Inter Tight\", \"Helvetica Neue\", Helvetica, Arial, sans-serif",
    labelSize: 16,
    counterSize: 16,
    coverTitleLarge: 124,
    coverTitleMedium: 108,
    coverTitleSmall: 96,
    subtitleSize: 21,
    promptBodySize: 22,
  },
};

export const splitEditorialV8Theme: CarouselTheme = {
  ...defaultCarouselTheme,
  canvas: threeByFourCanvas,
  spacing: {
    outerX: 90,
    outerY: 92,
    previewGap: 40,
  },
  colors: {
    ...defaultCarouselTheme.colors,
    fg: "#f5f0e9",
    muted: "#b6aca0",
    accent: "#c09a72",
    panel: "rgba(18, 16, 20, 0.84)",
    panelBorder: "rgba(255, 242, 224, 0.14)",
  },
  typography: {
    ...defaultCarouselTheme.typography,
    displayFamily: "\"DM Serif Display\", Georgia, serif",
    bodyFamily: "\"Space Grotesk\", \"Helvetica Neue\", Helvetica, Arial, sans-serif",
    labelSize: 16,
    counterSize: 16,
    coverTitleLarge: 104,
    coverTitleMedium: 94,
    coverTitleSmall: 82,
    subtitleSize: 19,
    promptHeadingSize: 24,
    promptBodySize: 21,
  },
  radius: {
    panel: 24,
  },
};

export const archiveSheetV9Theme: CarouselTheme = {
  ...defaultCarouselTheme,
  canvas: threeByFourCanvas,
  spacing: {
    outerX: 86,
    outerY: 88,
    previewGap: 40,
  },
  colors: {
    ...defaultCarouselTheme.colors,
    fg: "#f2ede4",
    muted: "#a89f92",
    accent: "#b59874",
    overlayStrong: "rgba(7, 7, 8, 0.82)",
    panel: "rgba(244, 238, 226, 0.08)",
    panelBorder: "rgba(255, 244, 224, 0.18)",
  },
  typography: {
    ...defaultCarouselTheme.typography,
    displayFamily: "\"Cormorant Garamond\", Georgia, serif",
    bodyFamily: "\"Space Grotesk\", \"Helvetica Neue\", Helvetica, Arial, sans-serif",
    labelSize: 15,
    counterSize: 16,
    coverTitleLarge: 110,
    coverTitleMedium: 98,
    coverTitleSmall: 84,
    subtitleSize: 19,
    promptHeadingSize: 26,
    promptBodySize: 20,
  },
  radius: {
    panel: 18,
  },
};

export const techLuxeV10Theme: CarouselTheme = {
  ...defaultCarouselTheme,
  canvas: threeByFourCanvas,
  spacing: {
    outerX: 90,
    outerY: 90,
    previewGap: 40,
  },
  colors: {
    ...defaultCarouselTheme.colors,
    bg: "#050608",
    fg: "#eef2f5",
    muted: "#97a2ab",
    accent: "#7c95aa",
    overlayStrong: "rgba(6, 8, 10, 0.86)",
    panel: "rgba(10, 13, 17, 0.88)",
    panelBorder: "rgba(171, 201, 228, 0.18)",
  },
  typography: {
    ...defaultCarouselTheme.typography,
    displayFamily: "\"Sora Variable\", \"Helvetica Neue\", Helvetica, Arial, sans-serif",
    bodyFamily: "\"Space Grotesk\", \"Helvetica Neue\", Helvetica, Arial, sans-serif",
    labelSize: 15,
    counterSize: 16,
    coverTitleLarge: 98,
    coverTitleMedium: 86,
    coverTitleSmall: 76,
    subtitleSize: 18,
    promptHeadingSize: 22,
    promptBodySize: 20,
    metaSize: 15,
    ctaSize: 16,
  },
  radius: {
    panel: 20,
  },
};

export const storySignalV11Theme: CarouselTheme = {
  ...defaultCarouselTheme,
  canvas: threeByFourCanvas,
  spacing: {
    outerX: 86,
    outerY: 86,
    previewGap: 40,
  },
  colors: {
    ...defaultCarouselTheme.colors,
    bg: "#0a0b0d",
    fg: "#f5f0e8",
    muted: "#a49a8c",
    accent: "#d37f4f",
    overlayStrong: "rgba(6, 6, 8, 0.82)",
    overlaySoft: "rgba(12, 12, 14, 0.2)",
    panel: "rgba(17, 18, 22, 0.86)",
    panelBorder: "rgba(255, 244, 224, 0.12)",
  },
  typography: {
    ...defaultCarouselTheme.typography,
    displayFamily: "\"DM Serif Display\", Georgia, serif",
    bodyFamily: "\"Inter Tight\", \"Helvetica Neue\", Helvetica, Arial, sans-serif",
    labelSize: 15,
    counterSize: 16,
    coverTitleLarge: 110,
    coverTitleMedium: 98,
    coverTitleSmall: 84,
    subtitleSize: 21,
    promptHeadingSize: 24,
    promptBodySize: 21,
    metaSize: 15,
    ctaSize: 18,
  },
  radius: {
    panel: 28,
  },
};

export const storyIvoryV12Theme: CarouselTheme = {
  ...defaultCarouselTheme,
  canvas: threeByFourCanvas,
  spacing: {
    outerX: 82,
    outerY: 82,
    previewGap: 40,
  },
  colors: {
    ...defaultCarouselTheme.colors,
    bg: "#f3ede3",
    fg: "#241f1a",
    muted: "#9a8065",
    accent: "#ce7647",
    overlayStrong: "rgba(32, 26, 20, 0.1)",
    overlaySoft: "rgba(255, 255, 255, 0.18)",
    panel: "rgba(255, 252, 247, 0.9)",
    panelBorder: "rgba(55, 43, 33, 0.08)",
  },
  typography: {
    ...defaultCarouselTheme.typography,
    displayFamily: "\"Cormorant Garamond\", Georgia, serif",
    bodyFamily: "\"Inter Tight\", \"Helvetica Neue\", Helvetica, Arial, sans-serif",
    labelSize: 15,
    counterSize: 16,
    coverTitleLarge: 104,
    coverTitleMedium: 92,
    coverTitleSmall: 80,
    subtitleSize: 20,
    promptHeadingSize: 24,
    promptBodySize: 21,
    metaSize: 15,
    ctaSize: 18,
  },
  radius: {
    panel: 26,
  },
};

export const storyBurntV13Theme: CarouselTheme = {
  ...defaultCarouselTheme,
  canvas: threeByFourCanvas,
  spacing: {
    outerX: 88,
    outerY: 88,
    previewGap: 40,
  },
  colors: {
    ...defaultCarouselTheme.colors,
    bg: "#8c4320",
    fg: "#fff5ee",
    muted: "rgba(255, 227, 208, 0.72)",
    accent: "#f5c38d",
    overlayStrong: "rgba(99, 42, 14, 0.2)",
    overlaySoft: "rgba(255, 255, 255, 0.06)",
    panel: "rgba(125, 60, 29, 0.34)",
    panelBorder: "rgba(255, 229, 207, 0.14)",
  },
  typography: {
    ...defaultCarouselTheme.typography,
    displayFamily: "\"Cormorant Garamond\", Georgia, serif",
    bodyFamily: "\"Inter Tight\", \"Helvetica Neue\", Helvetica, Arial, sans-serif",
    labelSize: 16,
    counterSize: 16,
    coverTitleLarge: 102,
    coverTitleMedium: 92,
    coverTitleSmall: 80,
    subtitleSize: 20,
    promptHeadingSize: 24,
    promptBodySize: 21,
    metaSize: 15,
    ctaSize: 18,
  },
  radius: {
    panel: 28,
  },
};

export const storyProofV14Theme: CarouselTheme = {
  ...defaultCarouselTheme,
  canvas: threeByFourCanvas,
  spacing: {
    outerX: 82,
    outerY: 82,
    previewGap: 40,
  },
  colors: {
    ...defaultCarouselTheme.colors,
    bg: "#f7f2ea",
    fg: "#181614",
    muted: "#9d866e",
    accent: "#d07f4f",
    overlayStrong: "rgba(0, 0, 0, 0.06)",
    overlaySoft: "rgba(255, 255, 255, 0.18)",
    panel: "rgba(255, 255, 255, 0.92)",
    panelBorder: "rgba(24, 22, 20, 0.08)",
  },
  typography: {
    ...defaultCarouselTheme.typography,
    displayFamily: "\"Sora Variable\", \"Helvetica Neue\", Helvetica, Arial, sans-serif",
    bodyFamily: "\"Inter Tight\", \"Helvetica Neue\", Helvetica, Arial, sans-serif",
    labelSize: 15,
    counterSize: 16,
    coverTitleLarge: 90,
    coverTitleMedium: 82,
    coverTitleSmall: 74,
    subtitleSize: 19,
    promptHeadingSize: 24,
    promptBodySize: 20,
    metaSize: 15,
    ctaSize: 17,
  },
  radius: {
    panel: 24,
  },
};

export const storyNoirV15Theme: CarouselTheme = {
  ...defaultCarouselTheme,
  canvas: threeByFourCanvas,
  spacing: {
    outerX: 88,
    outerY: 88,
    previewGap: 40,
  },
  colors: {
    ...defaultCarouselTheme.colors,
    bg: "#0a0a0b",
    fg: "#f4efe7",
    muted: "#a69480",
    accent: "#c57b4c",
    overlayStrong: "rgba(8, 8, 9, 0.88)",
    overlaySoft: "rgba(255, 255, 255, 0.03)",
    panel: "rgba(18, 17, 18, 0.86)",
    panelBorder: "rgba(255, 244, 224, 0.1)",
  },
  typography: {
    ...defaultCarouselTheme.typography,
    displayFamily: "\"DM Serif Display\", Georgia, serif",
    bodyFamily: "\"Space Grotesk\", \"Helvetica Neue\", Helvetica, Arial, sans-serif",
    labelSize: 15,
    counterSize: 16,
    coverTitleLarge: 98,
    coverTitleMedium: 88,
    coverTitleSmall: 78,
    subtitleSize: 19,
    promptHeadingSize: 24,
    promptBodySize: 20,
    metaSize: 15,
    ctaSize: 17,
  },
  radius: {
    panel: 22,
  },
};

export const manifestV16Theme: CarouselTheme = {
  ...defaultCarouselTheme,
  canvas: threeByFourCanvas,
  spacing: {
    outerX: 88,
    outerY: 80,
    previewGap: 40,
  },
  colors: {
    ...defaultCarouselTheme.colors,
    bg: "#f6f4f0",
    fg: "#111111",
    muted: "#888882",
    accent: "#111111",
    overlayStrong: "rgba(0, 0, 0, 0.04)",
    overlaySoft: "rgba(255, 255, 255, 0.14)",
    panel: "rgba(255, 255, 255, 0.0)",
    panelBorder: "rgba(17, 17, 17, 0.14)",
  },
  typography: {
    ...defaultCarouselTheme.typography,
    displayFamily: "\"Archivo Black\", \"Helvetica Neue\", Helvetica, Arial, sans-serif",
    bodyFamily: "\"Space Grotesk\", \"Helvetica Neue\", Helvetica, Arial, sans-serif",
    labelSize: 14,
    counterSize: 14,
    coverTitleLarge: 142,
    coverTitleMedium: 118,
    coverTitleSmall: 98,
    subtitleSize: 20,
    promptHeadingSize: 22,
    promptBodySize: 20,
    metaSize: 14,
    ctaSize: 18,
  },
  radius: {
    panel: 0,
  },
};

export const terminalV17Theme: CarouselTheme = {
  ...defaultCarouselTheme,
  canvas: threeByFourCanvas,
  spacing: {
    outerX: 62,
    outerY: 62,
    previewGap: 40,
  },
  colors: {
    ...defaultCarouselTheme.colors,
    bg: "#000000",
    fg: "#e0ffe0",
    muted: "#5a7a5a",
    accent: "#00ff88",
    overlayStrong: "rgba(0, 0, 0, 0.92)",
    overlaySoft: "rgba(0, 255, 136, 0.03)",
    panel: "rgba(0, 255, 136, 0.06)",
    panelBorder: "rgba(0, 255, 136, 0.2)",
  },
  typography: {
    ...defaultCarouselTheme.typography,
    displayFamily: "\"Space Grotesk\", \"Courier New\", monospace",
    bodyFamily: "\"Space Grotesk\", \"Courier New\", monospace",
    labelSize: 15,
    counterSize: 14,
    coverTitleLarge: 82,
    coverTitleMedium: 72,
    coverTitleSmall: 62,
    subtitleSize: 20,
    promptHeadingSize: 20,
    promptBodySize: 19,
    metaSize: 14,
    ctaSize: 17,
  },
  radius: {
    panel: 8,
  },
};

export const gazetteV18Theme: CarouselTheme = {
  ...defaultCarouselTheme,
  canvas: threeByFourCanvas,
  spacing: {
    outerX: 72,
    outerY: 72,
    previewGap: 40,
  },
  colors: {
    ...defaultCarouselTheme.colors,
    bg: "#f2ede4",
    fg: "#1a1816",
    muted: "#8a8078",
    accent: "#c23028",
    overlayStrong: "rgba(26, 24, 22, 0.88)",
    overlaySoft: "rgba(255, 255, 255, 0.06)",
    panel: "rgba(242, 237, 228, 0.96)",
    panelBorder: "rgba(26, 24, 22, 0.16)",
  },
  typography: {
    ...defaultCarouselTheme.typography,
    displayFamily: "\"DM Serif Display\", Georgia, \"Times New Roman\", serif",
    bodyFamily: "\"Inter Tight\", \"Helvetica Neue\", Helvetica, Arial, sans-serif",
    labelSize: 14,
    counterSize: 14,
    coverTitleLarge: 108,
    coverTitleMedium: 92,
    coverTitleSmall: 78,
    subtitleSize: 21,
    promptHeadingSize: 24,
    promptBodySize: 20,
    metaSize: 14,
    ctaSize: 17,
  },
  radius: {
    panel: 0,
  },
};

export const blueprintV19Theme: CarouselTheme = {
  ...defaultCarouselTheme,
  canvas: threeByFourCanvas,
  spacing: { outerX: 68, outerY: 68, previewGap: 40 },
  colors: {
    ...defaultCarouselTheme.colors,
    bg: "#1a2744",
    fg: "#d4e0f0",
    muted: "#7a92b4",
    accent: "#4da6ff",
    overlayStrong: "rgba(18, 28, 52, 0.9)",
    overlaySoft: "rgba(77, 166, 255, 0.06)",
    panel: "rgba(26, 39, 68, 0.8)",
    panelBorder: "rgba(77, 166, 255, 0.22)",
  },
  typography: {
    ...defaultCarouselTheme.typography,
    displayFamily: "\"Space Grotesk\", \"Courier New\", monospace",
    bodyFamily: "\"Inter Tight\", \"Helvetica Neue\", Helvetica, Arial, sans-serif",
    labelSize: 13, counterSize: 13,
    coverTitleLarge: 78, coverTitleMedium: 68, coverTitleSmall: 60,
    subtitleSize: 19, promptHeadingSize: 20, promptBodySize: 18,
    metaSize: 13, ctaSize: 16,
  },
  radius: { panel: 4 },
};

export const polaroidV20Theme: CarouselTheme = {
  ...defaultCarouselTheme,
  canvas: threeByFourCanvas,
  spacing: { outerX: 92, outerY: 92, previewGap: 40 },
  colors: {
    ...defaultCarouselTheme.colors,
    bg: "#e8e2d6",
    fg: "#2c2822",
    muted: "#8a8276",
    accent: "#c25a3c",
    overlayStrong: "rgba(44, 40, 34, 0.12)",
    overlaySoft: "rgba(255, 255, 255, 0.28)",
    panel: "rgba(255, 255, 252, 0.96)",
    panelBorder: "rgba(44, 40, 34, 0.06)",
  },
  typography: {
    ...defaultCarouselTheme.typography,
    displayFamily: "\"Cormorant Garamond\", Georgia, serif",
    bodyFamily: "\"Space Grotesk\", \"Helvetica Neue\", Helvetica, Arial, sans-serif",
    labelSize: 14, counterSize: 14,
    coverTitleLarge: 88, coverTitleMedium: 78, coverTitleSmall: 68,
    subtitleSize: 19, promptHeadingSize: 22, promptBodySize: 19,
    metaSize: 14, ctaSize: 17,
  },
  radius: { panel: 4 },
};

export const brutalistV21Theme: CarouselTheme = {
  ...defaultCarouselTheme,
  canvas: threeByFourCanvas,
  spacing: { outerX: 56, outerY: 56, previewGap: 40 },
  colors: {
    ...defaultCarouselTheme.colors,
    bg: "#d0d800",
    fg: "#000000",
    muted: "#3d3a00",
    accent: "#e8003a",
    overlayStrong: "rgba(0, 0, 0, 0.88)",
    overlaySoft: "rgba(230, 216, 0, 0.08)",
    panel: "rgba(0, 0, 0, 0.92)",
    panelBorder: "rgba(232, 0, 58, 0.4)",
  },
  typography: {
    ...defaultCarouselTheme.typography,
    displayFamily: "\"Archivo Black\", Impact, \"Helvetica Neue\", Helvetica, Arial, sans-serif",
    bodyFamily: "\"Space Grotesk\", \"Helvetica Neue\", Helvetica, Arial, sans-serif",
    labelSize: 16, counterSize: 16,
    coverTitleLarge: 136, coverTitleMedium: 112, coverTitleSmall: 94,
    subtitleSize: 22, promptHeadingSize: 24, promptBodySize: 21,
    metaSize: 15, ctaSize: 20,
  },
  radius: { panel: 0 },
};

export const vaporV22Theme: CarouselTheme = {
  ...defaultCarouselTheme,
  canvas: threeByFourCanvas,
  spacing: { outerX: 80, outerY: 80, previewGap: 40 },
  colors: {
    ...defaultCarouselTheme.colors,
    bg: "#0e0a1a",
    fg: "#f0e8ff",
    muted: "#8a7aaa",
    accent: "#e060ff",
    overlayStrong: "rgba(14, 10, 26, 0.86)",
    overlaySoft: "rgba(224, 96, 255, 0.06)",
    panel: "rgba(24, 18, 42, 0.78)",
    panelBorder: "rgba(224, 96, 255, 0.18)",
  },
  typography: {
    ...defaultCarouselTheme.typography,
    displayFamily: "\"Sora Variable\", \"Helvetica Neue\", Helvetica, Arial, sans-serif",
    bodyFamily: "\"Inter Tight\", \"Helvetica Neue\", Helvetica, Arial, sans-serif",
    labelSize: 15, counterSize: 15,
    coverTitleLarge: 96, coverTitleMedium: 84, coverTitleSmall: 74,
    subtitleSize: 19, promptHeadingSize: 22, promptBodySize: 20,
    metaSize: 14, ctaSize: 17,
  },
  radius: { panel: 28 },
};

export const redactV23Theme: CarouselTheme = {
  ...defaultCarouselTheme,
  canvas: threeByFourCanvas,
  spacing: { outerX: 78, outerY: 78, previewGap: 40 },
  colors: {
    ...defaultCarouselTheme.colors,
    bg: "#f0ece4",
    fg: "#1c1a18",
    muted: "#8a857c",
    accent: "#1c1a18",
    overlayStrong: "rgba(28, 26, 24, 0.82)",
    overlaySoft: "rgba(255, 255, 255, 0.12)",
    panel: "rgba(240, 236, 228, 0.92)",
    panelBorder: "rgba(28, 26, 24, 0.2)",
  },
  typography: {
    ...defaultCarouselTheme.typography,
    displayFamily: "\"Barlow Condensed\", \"Arial Narrow\", \"Helvetica Neue\", Helvetica, Arial, sans-serif",
    bodyFamily: "\"Space Grotesk\", \"Courier New\", monospace",
    labelSize: 14, counterSize: 14,
    coverTitleLarge: 108, coverTitleMedium: 94, coverTitleSmall: 82,
    subtitleSize: 19, promptHeadingSize: 22, promptBodySize: 19,
    metaSize: 13, ctaSize: 17,
  },
  radius: { panel: 0 },
};

export const neoprintV24Theme: CarouselTheme = {
  ...defaultCarouselTheme,
  canvas: threeByFourCanvas,
  spacing: { outerX: 74, outerY: 74, previewGap: 40 },
  colors: {
    ...defaultCarouselTheme.colors,
    bg: "#1a1a2e",
    fg: "#ffffff",
    muted: "#9090b0",
    accent: "#ff6b35",
    overlayStrong: "rgba(26, 26, 46, 0.88)",
    overlaySoft: "rgba(255, 107, 53, 0.06)",
    panel: "rgba(30, 30, 54, 0.82)",
    panelBorder: "rgba(255, 107, 53, 0.2)",
  },
  typography: {
    ...defaultCarouselTheme.typography,
    displayFamily: "\"Archivo Black\", \"Helvetica Neue\", Helvetica, Arial, sans-serif",
    bodyFamily: "\"Inter Tight\", \"Helvetica Neue\", Helvetica, Arial, sans-serif",
    labelSize: 14, counterSize: 14,
    coverTitleLarge: 104, coverTitleMedium: 92, coverTitleSmall: 80,
    subtitleSize: 20, promptHeadingSize: 22, promptBodySize: 20,
    metaSize: 14, ctaSize: 17,
  },
  radius: { panel: 16 },
};
